CREATE TABLE subjects (
	id					VARCHAR(30) NOT NULL PRIMARY KEY,
	age					SMALLINT NOT NULL,
	armlength			SMALLINT NOT NULL,
	armthickness		SMALLINT NOT NULL,
	chest				SMALLINT NOT NULL,
	ethnicity			SMALLINT NOT NULL,
	facialhaircolour	SMALLINT NOT NULL,
	facialhairlength	SMALLINT NOT NULL,
	figure				SMALLINT NOT NULL,
	haircolour			SMALLINT NOT NULL,
	hairlength			SMALLINT NOT NULL,
	height				SMALLINT NOT NULL,
	hips				SMALLINT NOT NULL,
	leglength			SMALLINT NOT NULL,
	legshape			SMALLINT NOT NULL,
	legthickness		SMALLINT NOT NULL,
	musclebuild			SMALLINT NOT NULL,
	necklength			SMALLINT NOT NULL,
	neckthickness		SMALLINT NOT NULL,
	proportions			SMALLINT NOT NULL,
	sex					SMALLINT NOT NULL,
	shouldershape		SMALLINT NOT NULL,
	skincolour			SMALLINT NOT NULL,
	weight				SMALLINT NOT NULL
);